import { Aside } from "@/components/aside";
import { Header } from "@/components/header";
import { Main } from "@/components/main";
import { geistVariables } from "@/fonts/geist";
import { isLocaleSupported } from "@/utils/isLocaleSupported";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import { notFound } from "next/navigation";
import "../globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode;
	params: { locale: string };
};

export default async function RootLayout({
	children,
	params,
}: RootLayoutProps) {
	const { locale } = await params;

	if (!isLocaleSupported(locale)) notFound();

	const translations = await getMessages();

	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={geistVariables}>
				<NextIntlClientProvider messages={translations}>
					<ThemeProvider>
						<Header />

						<div className="w-full max-w-[1200px] mx-auto flex relative">
							<Aside />

							<Main>{children}</Main>
						</div>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
